### ISSUE TITLE
syntax error: unexpected token

### ISSUE THREAD

**Issue by Esger** [alexzaworski/unit-golfer#7]
node v6.9.2
$ unit-golf 25vw
/usr/local/lib/node_modules/unit-golf/src/get-units-and-px-width.js:43
const getUnits = async ({ input, width, height }) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/unit-golf/src/index.js:1:90)
    at Module._compile (module.js:570:32)

**Comment by alexzaworski** [comment]
Yup, v6.9.2 doesn't support `async`. I've only tested on current LTS, though looking at https://node.green/#ES2017-features-async-functions it's possible >= 7.10.1 also works
